### ISSUE TITLE
.yaml file for component config

### ISSUE THREAD

**Issue by silveltman** [CloudCannon/bookshop#83]
Instead of a toml file, i would love to have the ability to use a yaml file for the config. 

When using 11ty/jekyll, this is way more in line with the SSG's developer experience. 

It would also save a lot of time when copying the data items/tags from the config file to a .md file or frontmatter

**Comment by bglw** [comment]
Hi @silveltman!

This is a great request. I'll look into what this would look like, especially around defining things like select fields and defaults. 

An upcoming project will require making some changes to the component config to align with the new [input configuration options in CloudCannon](https://cloudcannon.com/documentation/articles/how-to-choose-what-input-is-used-in-the-data-editor/) _(for example: how to make a field in the bookshop.toml a number slider rather than an input)_, so I might wait until that body of work has been done before expanding the set of supported types.

I'll keep you posted 🙏

**Comment by bglw** [comment]
Hello! This has been implemented in 3.0 😄 

See the [Migration Guide](https://github.com/CloudCannon/bookshop/blob/main/guides/migration.adoc) for the change between the files.

Running `npx @bookshop/up@latest` can also migrate all of your files to yml for you 🙌
